### ISSUE TITLE
Webpackbin link is not working

### ISSUE THREAD

**Issue by a-magdy** [vgrafe/react-range-progress#11]
I tried the Webpackpin link and it is not working, here is a screenshot:

![screen shot 2017-05-11 at 10 49 54](https://cloud.githubusercontent.com/assets/14139855/25940860/c963b5d0-3637-11e7-9cae-891ac6393882.png)

**Comment by vgrafe** [comment]
Thanks for reporting, I'll create a new fiddle on codesandbox very soon.

**Comment by vgrafe** [comment]
Done!

**Comment by a-magdy** [comment]
Cool, thank you :)

P.S: the old link is still in the repo description.
